plugins/modules/template_intent.py
Changes to create and delete project and other bug fixes
=> Changes to create and delete project and other bug fixes

plugins/modules/template_intent.py
Changes done:
1) Adding project description code in template intent module.
2) Improved pylint score
------------------------------------------------------------------
Your code has been rated at 9.66/10 (previous run: 9.66/10, +0.00)
3) ansible test results
(ansible) bash-3.2$ ansible-test sanity plugins/modules/template_intent.py
Running sanity test "action-plugin-docs"
Running sanity test "ansible-doc"
WARNING: Sanity test "ansible-doc" on Python 3.8 may be slow due to missing libyaml support in PyYAML.
Running sanity test "changelog"
Running sanity test "compile" on Python 2.7
WARNING: Skipping sanity test "compile" on Python 3.5 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 3.6 because it could not be found.
WARNING: Skipping sanity test "compile" …
=> Adding project description code in template intent module

plugins/module_utils/dnac.py, plugins/modules/template_intent.py
Changes done:
++++++++++++
1) Moved all generic methods and attributes to new class DnacBase. DnacBase is moved to dnac.py file.
2) All attributes will be move imported from DnacBase classs from dnac.py
3) Changes to fetch correct line number and function name from stackframe.
4) Fixed few log msgs.
ansible-test:
++++++++++
(ansible) bash-3.2$ ansible-test sanity plugins/modules/template_intent.py
Running sanity test "action-plugin-docs"
Running sanity test "ansible-doc"
WARNING: Sanity test "ansible-doc" on Python 3.8 may be slow due to missing libyaml support in PyYAML.
Running sanity test "changelog"
Running sanity test "compile" on Python 2.7
WARNING: Skipping sanity test "compile" on Python 3.5 because it could not be found.
WARNING: Skipping sanity test "compile" on Python 3.6 …
=> Moving generic api's to library and optimising intent modules

plugins/module_utils/dnac.py, plugins/modules/template_intent.py
ansible-test error fixes in dnac.py and template_intent.py files
=> Template intent minor fixes

plugins/module_utils/dnac.py, plugins/modules/network_settings_intent.py
Addressed reviewer comments for network_settings_intent.py and dnac.py
=> Addressed reviewer comments

playbooks/device_credential_intent.yml, plugins/modules/device_credential_intent.py, plugins/modules/network_settings_intent.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.9.txt
Device Credential Intent Module:
File Name - device_credential_intent.py
Create, Update, Delete Global Device Credential and Assign Device Credential to sites
Device Credential Intent Module Playbook:
File Name - device_credential_intent.yml
Playbook for the device_credential_intent.py
Network Settings Intent Module:
File Name: network_settings_intent.py
Changes in the documentation
=> Added new module and playbook for Device Credentials

plugins/module_utils/dnac.py, plugins/modules/device_credential_intent.py
Changes in the device_credentials_intent file and dnac.py 
used the validation_string for Check_task_response_status
=> Addressed the PR comments

playbooks/site_intent.yml, plugins/modules/site_intent.py
- Handle Idempotenacy in delete operation for site module if we run the same playbook again or if site not found.
- Convert the variables in the playbook and module documentation into snake-case to maintain uniformity across the modules.
=> Handle idempotenacy in delete operation and convert variable in snakecase convention and update documentation as well.

playbooks/device_credential_intent.yml, playbooks/device_details.yml, playbooks/network_settings_intent.yml, playbooks/template_pnp_intent.yml, plugins/module_utils/dnac.py, plugins/modules/device_credential_intent.py, plugins/modules/network_settings_intent.py, plugins/modules/template_intent.py
Network Settings Intent - Fixed issue with the message of the day key in the code, fixed the SNMP and Syslog servers updation issue, and Removed the servers.
Device Credential Intent - Camel Case to Snake Case, fixed the bug for throwing errors for multiple deletions
Template Intent - Camel Case to Snake Case, Skeleton for Export and Import Project/Template.
Playbooks - Updated Playbooks for all the above modules.
dnac.py - Updated check_task_response_status() function
=> Updated to snake cases, solved bugs and Enhancement

plugins/module_utils/dnac.py, plugins/modules/template_intent.py
Validating the output of the check_string_dictionary using isinstance in dnac.py file
=> Validating the output of the check_string_dictionary using isinstance

playbooks/device_credential_intent.yml
Added a new hierarchy for assigning device credentials to a site
=> Added a new hierarchy for assign device cred to a site

playbooks/test_swim_module.yml
Change the variable in the test_swim_module in snakecase so that it can also support swim_intent module operation.
=> change test_swim_module playbook variable in snakecase

playbooks/network_settings_intent.yml, plugins/module_utils/dnac.py, plugins/modules/network_settings_intent.py, plugins/modules/template_intent.py
Addressed the PR comments.
Added the validation structure in dnac.py and addressed template id issue.
Validation part changes have been done in network settings intent module.
=> Addressed the pr comments, added the validation structure in dnac.py and addressed template id issue

plugins/modules/template_intent.py
Resolved a bug on the variable mismatch on project_name and template_name
=> Resolved a bug on the variable mismatch on project_name and template_name

plugins/modules/device_credential_intent.py, plugins/modules/network_settings_intent.py
Validated the DNAC Global Device Credentials after applying the playbook config.
Made a sanity check in getting the network part from the playbook (Which gave an error while adding for the first time).
Addressed the review comments
=> Addressed the review comments. Validated the DNAC Global Device Credentials after applying the playbook config.

plugins/modules/discovery_intent.py
Fix: Documentation fix as requested to fix the spelling and documentation errors, along with few requests related to testing made in the testing group.
=> Making few changes in documentation of Discovery

playbooks/template_pnp_intent.yml, plugins/modules/template_intent.py
Validated the DNAC after applying the configuration template config. Addressed the PR comments.
=> Addressed the PR comments. Validated the DNAC after applying the configuration template config

plugins/modules/device_credential_intent.py
Set the logging levels for Device Credentails Intent module and Addressed the PR comments
=> Set the logging levels for Device Credentails Intent module and Addressed the PR comments

plugins/modules/device_credential_intent.py, plugins/modules/network_settings_intent.py, plugins/modules/template_intent.py
Set the logging levels, refactored the log statements, and addressed the review comments
=> Set the logging levels, refactored the log statements and addressed the review comments

plugins/modules/inventory_intent.py
Updated the argument of device_update --> device_updated in examples of inventory module.
=> update keyword in examples for device_updated in inventory module

plugins/module_utils/dnac.py
Changes the log message printing format
1. Added spaces after ':' operator
=> Changes the log message printing format

playbooks/credentials.template, playbooks/network_settings_intent.yml, plugins/module_utils/dnac.py, plugins/modules/network_settings_intent.py
Restructured the log messages.
Solved the bug which prints line no and function name of def log function.
Changed the class name from DnacNetwork -> NetworkSettings
Added the dnac_log_append and dnac_log_file_path in elem_spec and the documentation.
Added the new elem_spec parameters to the credentials.template file.
Addressed the review comments.
=> Restructured the log messages, solved the bug which prints line no and function name of log function

plugins/doc_fragments/intent_params.py
Changes in the dnac_log documentation
Aligned the documentation
=> Changes in the dnac_log documentation

plugins/modules/device_credential_intent.py, plugins/modules/discovery_intent.py, plugins/modules/inventory_intent.py, plugins/modules/network_settings_intent.py, plugins/modules/pnp_intent.py, plugins/modules/provision_intent.py, plugins/modules/site_intent.py, plugins/modules/swim_intent.py, plugins/modules/template_intent.py
Removed the documentation part of dnac_log_file_path and dnac_log_append and added it in intent_params.py
Check the availability of the credentials for assigning the credentials to the site.
Addressed the review comments.
=> Removed the documentation part of dnac_log_file_path and dnac_log_append, check the credentials are available for the assign credentials

playbooks/device_credential_workflow_manager.yml, playbooks/network_settings_workflow_manager.yml, playbooks/template_workflow_manager.yml
Removed the unnecessary comments from the playbook for the following modules,
1. network_setting_workflow_manager.yml
2. device_credential_workflow_manager.yml
3. template_workflow_manager.yml
=> Removed the unnecessary comments from the playbook

plugins/doc_fragments/workflow_manager_params.py, plugins/module_utils/dnac.py
Added a global documentation file for all the workflow_manager modules with the name workflow_manager_params.py
=> Added a global documentation file for all the workflow_manager modules

plugins/modules/device_credential_workflow_manager.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/template_workflow_manager.py
Changed the global documentation from the intent_params to workflow_manager_params
=> Changed the global documentation from the intent_params to workflow_manager_params

plugins/modules/device_credential_workflow_manager.py, plugins/modules/inventory_workflow_manager.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/site_workflow_manager.py, plugins/modules/swim_workflow_manager.py, plugins/modules/template_workflow_manager.py
Changed the term intent to workflow_manager in the class description and changed the global documentation to workflow_manager_params from intent_params
=> Changed the term intent to workflow_manager in the class description

plugins/modules/device_credential_workflow_manager.py, plugins/modules/inventory_workflow_manager.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/site_workflow_manager.py, plugins/modules/swim_workflow_manager.py
Changed the copyright of the modules to 2024
=> Changed the copyright of the modules to 2024

plugins/modules/discovery_workflow_manager.py, plugins/modules/pnp_workflow_manager.py
Description: Changing naming conventions as per the required one i.e. Workflow manager. Added Cisco Catalyst Center instead of DNAC in the documentation and code
=> Adding workflow manager codes for Discovery and PnP

playbooks/device_provision_workflow.yml, plugins/modules/discovery_workflow_manager.py, plugins/modules/pnp_workflow_manager.py, plugins/modules/provision_workflow_manager.py
Description: Adding provision workflow and its sample playbook.
Test cases covered: Wired provision, reprovision and unprovision.
Limitations: Wireless provisioning
=> Adding Playbook and Code for Provision workflow manager

plugins/modules/discovery_workflow_manager.py
Problem: Error while filtering out IPs on the CLI.
Fix: Have added one more elif condition for the check.
Test cases: Have tested with newly added HTTP credentials.
=> Adding small changes post testing in Discovery

plugins/modules/discovery_intent.py
Description: We have made a few changes in the Discovery Workflow module. Pushing the same changes in the intent Module.
=> Pushing the latest changes in Intent module

playbooks/network_settings_intent.yml, playbooks/network_settings_workflow_manager.yml, plugins/modules/network_settings_intent.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/template_intent.py, plugins/modules/template_workflow_manager.py
1. Added the detailed description for the reserve ip pool and global pool.
2. Explained the choices in the documentation.
3. Solved the ipv4 gateway problem. previously it was overwriting the ipv4gateway.
4. Some camel cases were used in the documentation and the code part. Now I removed everything.
5. Basic playbook were run.
=> Added detailed description in the documentation and problem fixed for ipv4 gateways

plugins/modules/swim_intent.py, plugins/modules/swim_workflow_manager.py
In this commit -
-- Address the PR review comment in the documentation of Swim intent and workflow manager modules.
=> Address PR review comments on swim module

plugins/modules/inventory_intent.py, plugins/modules/inventory_workflow_manager.py, plugins/modules/swim_intent.py, plugins/modules/swim_workflow_manager.py
In this commit -
-- add string while checking snmp_version for updating device details which gets missed while committing the previous code.
=> add string while checking snmp_version for updating device details

changelogs/changelog.yaml, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py, plugins/modules/inventory_intent.py, plugins/modules/inventory_workflow_manager.py, plugins/modules/swim_intent.py, plugins/modules/swim_workflow_manager.py
Addressed the review comments and changed the documentation as per the ansible-galaxy documentation guidelines
=> Changed the documentation as per the ansible-galaxy coding guidelines

changelogs/changelog.yaml
Updated the changelog.yaml about the stack switch getting converted to normal switch.
=> Updated the changelog.yaml about the stack switch getting converted to normal switch.

plugins/modules/template_workflow_manager.py
Made the import project and export template/project work for the SDK
=> Made the import project and export template/project work for the SDK

playbooks/discovery_intent.yml, playbooks/discovery_workflow_manager.yml, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
1.  **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/198
2.  **Problem Description**: User sees that Discovery gets failed on the CLI but it gets passed on the GUI.
3.  **Root Cause:** This was happening because of an or condition added previously.
4.  **Code Changes**: Removed or and added a continue statement to take care of both In progress and Inverstory service restart.
5. **Testing and Automation**:  For testing we tried to get the logs from the team which executed it successfully. Here is the tail of the logs attached.
_03-18-2024 23:33:05 DEBUG  Discovery: create_discovery: 1265: The response received post discovery creation API called is {'response': {'taskId': 'c6851109-c38c-40b0-bd3d-b762aaa7667c', 'url': …
=> Adding fix for intermittent failure of Discovery

plugins/modules/site_intent.py, plugins/modules/site_workflow_manager.py
In this commit-
-- Fix the issue of keyerror - 'building'. while creating other type of site like floor and area.
=> fix the issue of key error building while creating other type of site.

playbooks/PnP.yml, playbooks/PnP_Workflow_Manager_Playbook.yml, playbooks/device_provision_workflow.yml, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py, plugins/modules/pnp_intent.py, plugins/modules/pnp_workflow_manager.py, plugins/modules/provision_intent.py, plugins/modules/provision_workflow_manager.py
Fix: Adding op_modifies as true for all the modules, to bypass the internal check of dnacentersdk
=> Making OP_modifies as true

playbooks/device_details.template, playbooks/template_workflow_manager.yml, plugins/module_utils/dnac.py, plugins/modules/template_workflow_manager.py
Review - 1 [03-04-2024 (DD/MM/YYYY]
Import Template should input JSON file for user convenience
Added the new feature to the import_template part and added two functions to the dnac.py
Checked the code by passing the JSON file path and imported the template.
=> Added the new feature for importing a template using JSON file

playbooks/network_settings_workflow_manager.yml, plugins/modules/network_settings_workflow_manager.py
Added a new feature on reserved pool (Accessing using the name of the global pool)
Made the global pool and the reserve pool work for multiple elements in a list
=> Added a new feature on reserved pool (Accessing using the name of the global pool)

plugins/modules/network_settings_workflow_manager.py
Eliminated the useless and redundant variables and optimised the code, made some changes in the logs
=> Eliminated the useless and redundant variables and optimised the code, made some changes in the logs

plugins/modules/network_settings_workflow_manager.py
Resolved the problem with the snmp and syslog servers updation.
1. While fetching the data if it is there is no snmp or syslog configured, updation is not happening.
=> Resolved the problem with the snmp and syslog servers updation.

playbooks/device_credential_workflow_manager.yml, plugins/modules/device_credential_workflow_manager.py
Review - 1 [24-04-2024 (DD/MM/YYYY]
Delete credentials returns a 'NoneType' error in the verify_diff_deleted() method
Missed an if check for the credential availability in the self.have
Added the if condition before fetching the item from the self.have
Tested the code changes with config_verify=True and with the provided playbook.
=> Added a check for the global device credentials while verifying the config

plugins/module_utils/dnac.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/template_workflow_manager.py
Added new features and resolved the bugs for the network settings and template workflow manager modules
=> Added new features and resolved the bugs for the network settings and template workflow manager modules

playbooks/ise_radius_integration_workflow_manager.yml, plugins/module_utils/dnac.py, plugins/modules/ise_radius_integration_workflow_manager.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/template_workflow_manager.py
Addressed the review comments and added a log message for checking the existence of the file path
=> Addressed the review comments and added a log message for checking the existence of the file path

plugins/modules/template_workflow_manager.py
Removed the unused failure_params parameter from configuration_templates and export templates
=> Removed the unused failure_params parameter from configuration_templates and export templates

plugins/modules/device_credential_workflow_manager.py
Prompts an error when the site_name is invalid under assign_credentials_to_site
=> Prompts an error when the site_name is invalid under assign_credentials_to_site

plugins/modules/template_workflow_manager.py
Verified the config of containingTemplates under configuration_templates
=> Verified the config of containingTemplates under configuration_templates

plugins/modules/template_workflow_manager.py
Fixed the issue with passing more than one element in containingTemplates
=> Fixed the issue with passing more than one element in containingTemplates

plugins/modules/template_workflow_manager.py
Removed the unused variables which shows no effect on the GUI
"rollbackTemplateContent" and "ollbackTemplateParams"
=> Removed the unused variables which shows no effect on the GUI

changelogs/changelog.yaml
Added the removed variables in the changelogs.yaml
=> Added the removed variables in the changelogs.yaml

plugins/modules/network_settings_workflow_manager.py
Fixed the parameter confusion between the ipAddress and network for ISE
Making the timezone to a non mandatory field
=> Fixed the parameter confusion between the ipAddress and network for ISE

plugins/modules/network_settings_workflow_manager.py
Changed the netflow_collector port unavailability from None to 'null'
=> Changed the netflow_collector port unavailability from None to 'null'

playbooks/device_provision_workflow.yml, plugins/modules/provision_workflow_manager.py
**1. Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/250
**2. Problem Description:** Need of assigning devices to site in provisioning module and adding new message for re-provisioning of devices
**3. Code Changes:**  Added a new parameter called provisioning in the module which when set to false will only assign and when true will do provisioning. Along with that have added the code for different message for re-provisioning.
=> PR for assigning device to site

plugins/modules/network_settings_workflow_manager.py
Resolved the conflict when reserving a global pool which shows the config is not applied to the DNAC
=> Resolved the conflict when reserving a global pool which shows the config is not applied to the DNAC

plugins/modules/ise_radius_integration_workflow_manager.py
Resolved the type problems, extra indentation and documentation issues.
=> Resolved the type problems, extra indentation and documentation issues.

plugins/modules/network_settings_workflow_manager.py
Since the Reserve pool get API have a limit of 25. Made the get_reserve_pool iterate after 25 values.
=> Since the Reserve pool get API have a limit of 25. Made the get_reserve_pool iterate after 25 values.

plugins/modules/network_settings_workflow_manager.py
Resolved the problem with the prev_name for Global Pool and Reserve Pool
=> Resolved the problem with the prev_name for Global Pool and Reserve Pool

playbooks/ise_radius_integration_workflow_manager.yml, plugins/modules/ise_radius_integration_workflow_manager.py
Supports the ISE server 'username' and 'password' updation, made port number default to 49
=> Supports the ISE server 'username' and 'password' updation, made port number default to 49

playbooks/device_provision_workflow.yml, plugins/modules/provision_workflow_manager.py
**1. Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/263
**2. Problem Description:** Provisioning wireless devices to a site
**3. Code Changes:**  Fixed the payload for the wireless provisioning API. Added conditions to check the re-provisioning part.
**4. Follow-up Tasks:** Will need to work on the assigning to site part for wireless devices.
**5.  Testing and Automation:** Tested for wireless WLC provisioning and re-provisioning.
TASK [Provision a wireless device to a site] ***********************************************************************************************************************************************************
PLAY RECAP ********************************************************************************************************************************** …
=> Adding feature of wireless provisioning and reprovisioning

plugins/modules/device_credential_workflow_manager.py
Fixed the problem with the sites in assign_device_credentials
=> Fixed the problem with the sites in assign_device_credentials

plugins/modules/network_compliance_workflow_manager.py
**PR Summary:**
- Code Changes have been made to the plugins/modules/network_compliance_workflow_manager.py file only. 
- Includes 2 Bug Fixes:
1. Compliance is already In-progress for the device (race condition)
2. Sync configuration: OK status for devices with already compliance RUNNING_CONFIG, not FAILED
- Tested on DNAC v2.3.7.6 Test Bed.
=> 2 Bug Fixes - Network Compliance Module

changelogs/changelog.yaml, playbooks/ise_radius_integration_workflow_manager.yml, plugins/modules/ise_radius_integration_workflow_manager.py
Removed the subscriber_name for the ISE server. Made required for minimal params for updation
=> Removed the subscriber_name for the ISE server. Made required for minimal params for updation

plugins/modules/ise_radius_integration_workflow_manager.py
Removed the params which cannot be updated from the example playbook
=> Removed the params which cannot be updated from the example playbook

plugins/modules/network_settings_workflow_manager.py
Verifying the existence of servers in the network_aaa and clientandEndpoint_aaa
=> Verifying the existence of servers in the network_aaa and clientandEndpoint_aaa

plugins/modules/network_compliance_workflow_manager.py
**PR Summary:**
- Code changes have been made only to the plugins/modules/network_compliance_workflow_manager.py file. 
- Fixes Include:
1.    Enhancement: Changed function="get_compliance_detail" to function="compliance_details_of_device"
- Tested on Catalyst Centre v2.3.7.0
Note: 
- This PR also includes a code change from previous PR, rectified a Log Message.
=> 1 Enhancement -  Network Compliance Module

plugins/modules/ise_radius_integration_workflow_manager.py
Gave different error message for 'INPROGRESS' and 'FAILED' state
Changed the ise_integration_wait_time maximum limit from 60 to 100
=> Gave different error message for 'INPROGRESS' and 'FAILED' state

plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
**1. Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/282
**2. Problem Description:** Changing the name of the snmp read write credential name from desc to description
**3.  Code Changes:** Made changes in the code and documentation.
=> Changing the name from desc to description

plugins/modules/ise_radius_integration_workflow_manager.py
Added a maximum timeout for running a infinite loop
=> Added a maximum timeout for running a infinite loop

plugins/module_utils/dnac.py, plugins/modules/ise_radius_integration_workflow_manager.py
Return a failure message when the task or execution is not compeleted within the given time
=> Return a failure message when the task or execution is not compeleted within the given time

plugins/modules/device_credential_workflow_manager.py
Changes made to make the module inline with the IT cases
=> Changes made to make the module inline with the IT cases

plugins/module_utils/dnac.py
Added a function to check the task tree when the failure response asks to check the task tree
=> Added a function to check the task tree when the failure response asks to check the task tree

plugins/modules/network_compliance_workflow_manager.py
PR Summary:
Code changes are only in the plugins/modules/network_compliance_workflow_manager.py file. 
Includes 2 Bug Fixes:
1. Run Compliance Check timeout return FAILED
2. Can not get compliance details when AP present in IP list
Code Changes:
- Added run_compliance_batch_size parameter
- Added dnac_api_task_timeout paramter
- Replaced get_compliance_details with compliance_details_of_device API for both run_compliance and syn_device_config operations
- Modified code to run compliance operation in provided batch size (Recursive)
- Modifications to match the Function Definitions and Docstrings standards
=> 2 Bug Fixes: network compliance module

plugins/modules/network_settings_workflow_manager.py
Fixed the problem of not accepting the public IPs of the ISE server under network_aaa and client_and_endpoint_aaa
=> Fixed the problem of not accepting the public IPs of the ISE server under network_aaa and client_and_endpoint_aaa

plugins/modules/ise_radius_integration_workflow_manager.py
Made the check for the status of the task id as a common function
=> Made the check for the status of the task id as a common function

plugins/modules/device_configs_backup_workflow_manager.py
1. **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/300
2. **Problem Description:** If pyzipper module is not present, it skips the issue instead of failing.
3. **Root Cause**: Haven't done proper error handling.
4. **Code Changes**: Added fail_json if pyzipper is not present.
5. **Testing**: Have tested it by uninstalling pyzipper and installing pyzipper
=> Fixing pyzipper issue

playbooks/device_details.template, plugins/modules/template_workflow_manager.py
Support for importing the project using JSON file
=> Support for importing the project using JSON file

playbooks/network_settings_workflow_manager.yml, plugins/modules/network_settings_workflow_manager.py
Support for the network servers and management under different  sites
=> Support for the network servers and management under different  sites

playbooks/ise_radius_integration_workflow_manager.yml, plugins/modules/ise_radius_integration_workflow_manager.py
Support for multiple authentication and policy servers
=> Support for multiple authentication and policy servers

plugins/modules/network_settings_workflow_manager.py
Fixed the problem with the shared_secret updation
=> Fixed the problem with the shared_secret updation

plugins/modules/template_workflow_manager.py
Added the sanity validation for export templates
=> Added the sanity validation for export templates

plugins/modules/events_and_notifications_workflow_manager.py
In this commit --
-- Fix the typo error from desination --> destination in the events and notifications workflow manager module.
=> Fix the typo error in the module.

plugins/modules/device_configs_backup_workflow_manager.py
Backup of devices associated with a site can be taken using the "site" parameter.
=> Adding site as a parameter for device configs backup

playbooks/sda_extranet_policies_workflow_manager.yml, plugins/modules/sda_extranet_policies_workflow_manager.py, plugins/modules/site_workflow_manager.py, tests/integration/ccc_site_management/vars/vars_site_management.yml
Added SDA Extranet Policies Workflow Manager
This module is designed to manage the following operations for SDA Extranet Policies:
•	Add: Create new extranet policies.
•	Update: Modify existing extranet policies.
•	Delete: Remove existing extranet policies.
Two files have been added:
1. plugins/modules/sda_extranet_policies_workflow_manager.py
2. playbooks/sda_extranet_policies_workflow_manager.yml
- [yes ] New feature
- [ yes] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [yes ] I have made corresponding changes to the documentation
- [yes ] My changes generate no new warnings
- [pending ] I have added tests that prove my fix is effective or that my …
=> Added Module - SDA Extranet Policy 

plugins/modules/site_workflow_manager.py, tests/integration/ccc_site_management/vars/vars_site_management.yml
=> test commit

plugins/modules/network_settings_workflow_manager.py
Optimized the code for the reserving the subpool from the global pool
- [ no ] Bug fix
- [ yes ] New feature
- [ no ] I have commented my code, particularly in hard-to-understand areas
- [ yes ] All the sanity checks have been completed and the sanity test cases have been executed
- [ yes ] Tasks are idempotent (can be run multiple times without changing state)
- [ no ] Variables and secrets are handled …
=> Optimized the code for the reserving the subpool from the global pool

playbooks/user_role_workflow_manager.yml, plugins/modules/user_role_workflow_manager.py, tests/unit/modules/dnac/test_user_role_workflow_manager.py
- [ yes ] I have made corresponding changes to the documentation
- [ yes ] Any dependent changes have been merged and published in downstream modules
- [ yes ] All the sanity checks have been completed …
=> Updated user and role workflow feature

.circleci/config.yml, .github/workflows/integration_tests.yml, .github/workflows/main.yml, .github/workflows/release-prep.yml, .github/workflows/release.yml, CODEOWNERS
Hi Madhan,
To make this change applicable some things need to be done:
1. CircleCI Project API token need to be added to Github Actions secrets so we can trigger builds https://circleci.com/docs/managing-api-tokens/#creating-a-project-api-token
2.  To make auto-merge working you need to set branch protection rules for main branch. Add there ci/circleci: sanity-tests as required CI check
3. Add CODEOWNERS file support in repo settings
IP addresses are still visible, i will consider your suggestions after I'll come back from vacation and implement it.
If something is unclear write to me on webex, i will try to help you in spare time.
=> Run CI on PR approve

plugins/modules/rma_workflow_manager.py
- [ yes ] All the sanity checks have been completed …
=> RMA bug fixed

tests/unit/modules/dnac/fixtures/site_workflow_manager.json, tests/unit/modules/dnac/test_site_workflow_manager.py
- [ No] Bug fix
- [ Yes] New feature
- [ No] Breaking change
- [ No] Documentation update
- [ Yes] My code follows the style guidelines of this project
- [ Yes] I have performed a self-review of my own code
- [Yes ] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have made corresponding changes to the documentation
- [Yes] My changes generate no new warnings
- [ Yes] I have added tests that prove my fix is effective or that my feature works
- [Yes ] New and existing unit tests pass locally with my changes
- [Yes ] Any dependent changes have been merged and published in downstream modules
- [ Yes] All the sanity checks have been completed and the sanity …
=>  UT code for site workflow manager

plugins/modules/user_role_workflow_manager.py
- [ yes ] All the sanity checks have been completed …
=> user role workflow feature bugs fixed

playbooks/rma_workflow_manager.yml, plugins/modules/rma_workflow_manager.py
- [ yes ] All the sanity checks have been completed …
=> Unmarking device for replacement 400 error - bug fixed

plugins/modules/user_role_workflow_manager.py
The following bugs have been addressed in the commit.
1. [CSCwm13546] "Mandatory field not present: An error occurred while creating the user" - Execption miss cases.
2. [CSCwm10583] Username Validation Issues in User and Role Workflow Manager.
3. [CSCwm11547] Unexpected Behavior in Name Field Validation.
4. [CSCwm13900] Incorrect Example Role Configuration in User Role Workflow Manager.
5. [CSCwm10272] Inaccurate Error Message for Duplicate User Creation.
6. [CSCwm04316] Inconsistency in User and Role Workflow Manager Required Parameters.
7. [CSCwm12376] There are some issues with the 'add_role_api' function in the document.
- [ yes …
=> user_role_workflow_feature bugs fixed

plugins/modules/accesspoint_workflow_manager.py
=> Bug raised for the 9 issue was fixed.

plugins/modules/accesspoint_workflow_manager.py
To support Clean air changed V1 to V2 in Update AP configuration
=> AP update V1 to V2 to support clean air

plugins/module_utils/dnac.py, plugins/modules/user_role_workflow_manager.py
The below issue is fixed 
1 Security Issue: Plaintext Password Storage in User and Role Workflow Manager
- [ yes ] All the sanity checks have been completed and …
=> user_role_workflow_manager bug fixed

plugins/module_utils/dnac.py, plugins/modules/accesspoint_workflow_manager.py, tests/unit/modules/dnac/test_accesspoint_workflow_manager.py
1) [CSCwm12710] isAssignedSiteAsLocation parameter missing - fixed
2) [CSCwm31233] IPv6 is getting rejected as controller IP
3) [CSCwm33299] Current AP provision API used in module is deprecated since 2.3.7.6
4) [CSCwm14389]  Radio configuration returns false negative
=> Accesspoint update feature all fields

plugins/modules/ise_radius_integration_workflow_manager.py, plugins/modules/network_settings_workflow_manager.py
Added try catch block for all the SDK calls for managing the Global Pool, Reserve Pool, Network Functions.
Added the missing increment state while deleting the Authentication and Policy Server from the Cisco Catalyst Center.
Added a new check to verify whether the Cisco ISE is ready to accept the certificate or not
=> Added the try catch block for the all the SDK calls and added the missing increment state while deleting the Auth server

plugins/module_utils/dnac.py
Fix for the infinte loop in the module.
Changes in the log messages for the response validation.
Added the line no while logging during the check_return_status check.
=> Fix for the infinte loop in the module.

plugins/module_utils/dnac.py, plugins/modules/ise_radius_integration_workflow_manager.py
Routes for the ise integration message in DNAC versions 2.3.7.6 and 2.3.7.9
'operation successful' for the DNAC version 2.3.7.9 and
'operation sucessful' for the DNAC version 2.3.7.6
=> Routes for the ise integration message in DNAC versions 2.3.7.6 and 2.3.7.9

plugins/module_utils/dnac.py, plugins/modules/user_role_workflow_manager.py
The below issue is fixed
Unclear Error Message for Missing Mandatory Field in User Creation
- [ yes ] All the sanity checks have been completed and the sanity test …
=> User and Role comments fixed

plugins/modules/network_settings_workflow_manager.py
Changed the pan_address and primary_server_address key value for ISE servers
=> Changed the pan_address and primary_server_address key value for ISE servers

plugins/modules/template_workflow_manager.py
Checked the project name for verifying the absence of the template
=> Checked the project name for verifying the absence of the template

plugins/module_utils/dnac.py
Common name changes on the output of playbook
=> Common function naming issue fixed

plugins/modules/provision_workflow_manager.py
Code fix in provision workflow manager
- [no  ] Breaking change
- [ yes ] Documentation update
- [yes ] I have performed a self-review of my own code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [ yes] I have made corresponding changes to the documentation
- [yes ] My changes generate no new warnings
- [ no] I have added tests that prove my fix is effective or that my feature works
- [ no] New and existing unit tests pass locally with my changes
- [ yes] All the sanity checks have been completed and the sanity test cases have been executed
- [ yes] Tasks are idempotent (can …
=> provision workflow manager code fix

plugins/module_utils/dnac.py
Added version based on the Assign devices to site common function requested by team.
=> Updated version based for assign devices to site to use by others

playbooks/sda_host_port_onboarding_workflow_manager.yml, plugins/modules/sda_extranet_policies_workflow_manager.py, plugins/modules/sda_host_port_onboarding_workflow_manager.py
Add 2 New  SDA Module :
1. SDA Host Port Onboarding - sda_host_port_onboarding_workflow_manager
Manage host onboarding operations such as adding, updating, and deleting port assignments and port channels of Network Devices in SD-Access Fabric.
2. SDA Extranet Policies Module - sda_extranet_policies_workflow_manager
Manage SDA Extranet Policies in SD-Access Fabric.
**Added two new files:**
1. playbooks/sda_host_port_onboarding_workflow_manager.yml
3. plugins/modules/sda_host_port_onboarding_workflow_manager.py
4.  plugins/modules/sda_extranet_policies_workflow_manager.py
=> Added 2 New SDA Modules - SDA Host Port Onboarding & SDA Extranet Policies Module

plugins/modules/swim_workflow_manager.py
Bug fix for the SWIM workflow manager 
- [ yes] New and existing unit tests pass locally with my changes
- [ no] Any dependent changes have been merged and published in downstream modules
- [ yes ] All the sanity checks have been completed and the sanity test cases have been executed
- [ yes] Tasks are idempotent …
=> Swim workflow feature enhansment

plugins/module_utils/dnac.py, plugins/modules/accesspoint_workflow_manager.py
71649 - Duplicate Entries for Controllers doesn't return any error
80229 - Disallowed characters for AP name are being accepted by the module
75377 - Invalid IPv6 in controller IP doesn't return any Error.
=> AP Workflow 3 bug fixed in this pull req

plugins/modules/network_settings_workflow_manager.py
Issue 76593: NW Settings - The validation for updating AAA servers is incorrect
- [ Yes] Bug fix
- [No ] New feature
- [ No] Breaking change
- [No ] Documentation update
- [ Yes] My code follows the style guidelines of this project
- [ Yes] I have performed a self-review of my own code
- [ Yes] I have commented my code, particularly in hard-to-understand areas
- [ Yes] I have made corresponding changes to the documentation
- [ Yes] My changes generate no new warnings
- [ No] I have added tests that prove my fix is effective or that my feature works
- [ Yes] New and existing unit tests pass locally with my changes
- [ Yes] Any dependent changes have been merged and published in downstream modules
- [ Yes] All the sanity checks have been completed and the sanity test cases have been …
=> The validation for updating AAA servers is incorrect

plugins/module_utils/dnac.py, plugins/modules/user_role_workflow_manager.py
The below issue is fixed
1 Insufficient Permissions for Admin User to Create Roles
- [ yes ] All the sanity checks have been completed and the sanity test cases …
=> User and Role bug fixed

plugins/modules/accesspoint_workflow_manager.py
71823 - Channel width param returns inappropriate error.
71980 - Channel Width validation needs an update
71867 - Antenna Gain Config on unsupported AP doesn't return appropriate error
=> Accesspoint feature enhancement

plugins/modules/ise_radius_integration_workflow_manager.py
Fixed the problem while editing AAA server return 'list index out of range' error
=> Fixed the problem while editing AAA server return 'list index out of range' error

plugins/modules/pnp_workflow_manager.py
PNP workflow enhancement code changes.
=> Pnp workflow enhancement

plugins/modules/network_settings_workflow_manager.py
- [ Yes] Bug fix
- [ No] New feature
- [ No] Breaking change
- [No ] Documentation update
- [ Yes] My code follows the style guidelines of this project
- [Yes ] I have performed a self-review of my own code
- [ Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes ] I have made corresponding changes to the documentation
- [Yes ] My changes generate no new warnings
- [Yes ] I have added tests that prove my fix is effective or that my feature works
- [ Yes] New and existing unit tests pass locally with my changes
- [Yes ] Any dependent changes have been merged and published in downstream modules
- [Yes ] All the sanity checks have been completed and the …
=> 	Unable to configure Global and Site-specific network settings 

plugins/modules/provision_workflow_manager.py
This PR is regarding the enhancement of provision workflow module.
- [ no ] Bug fix
- [ yes ] New feature
- [ yes ] All the sanity checks have been completed and the sanity test cases have been executed …
=> provision workflow module

plugins/modules/sda_fabric_devices_workflow_manager.py
Tested the code for fabric devices and L3 Handoff with IP Transit
=> Tested the code for fabric devices and L3 Handoff with IP Transit

plugins/modules/ise_radius_integration_workflow_manager.py
Implemented the idempotent state for the Cisco ISE server updation
=> Implemented the idempotent state for the Cisco ISE server updation

plugins/modules/site_workflow_manager.py
=> Modifications for site_enhancement_module

plugins/modules/sda_fabric_devices_workflow_manager.py
Tested the L2 Handoff and L3 Handoff with SDA Transit
=> Tested the L2 Handoff and L3 Handoff with SDA Transit

plugins/modules/pnp_workflow_manager.py
96002 - Cannot claim devices; pnp module incorrectly states the device does not exist
=> PNP device claim bug fixed
