madhansansel/dnacenter-ansible

playbooks/device_provision.yml, plugins/modules/provision_intent.py
Problem description:  To add the code for device provisioning from the inventory (wired and wireless). Have worked on the review comments as well.
Fix: Added the code for wired and wireless provisioning
Testing information: Tested for wired. Wireless API is having issues in provisioning
Dependancies SDK 2.6.10
Limitations: Unprovision/deletion is not added yet
=> Adding code for provisioning (wired is validated)

plugins/modules/inventory_intent.py
In this commit - 
-- Added the code for Assigning Wireless Devices to Site and then do Provisioning.
-- Add examples and parameters in the Documentation.
-- Write doctstring for each API.
Limitation:
-- Testing pending as Provision API for Wireless giving issue in DNAC GUI as well.
=> Provision Wireless devices, add examples in documentation

playbooks/network_settings_intent.yml, plugins/module_utils/dnac.py, plugins/modules/device_credential_intent.py, plugins/modules/network_settings_intent.py, plugins/modules/template_intent.py
Supported both the camel and snake case for device_credentials_intent.py, template_intent.py, and network_settings_intent.py and added a new function in the dnac.py.
Added a log in the camel_to_snake_case function.
As we have used camel for the Release v6.8.1 (https://github.com/cisco-en-programmability/dnacenter-ansible/releases/tag/v6.8.1) and changed those camel case to snake case in the Release v6.10.0 (https://github.com/cisco-en-programmability/dnacenter-ansible/releases/tag/v6.10.0). So we are supporting both the camel case and snake case now.
=> Supported both the camel and snake case.

plugins/modules/discovery_intent.py, plugins/modules/pnp_intent.py
Problem Description: Logging based on various levels (CRITICAL, ERROR, WARNING, INFO, DEBUG)
Fix: We have added dnac_log_levels
Test cases: Have tested for default (WARNING and DEBUG)
Results: 1. WARNING gives logs for WARNINGS, CRITICAL AND ERROR
2.  DEBUG logs all the messages including CRITICAL, ERROR, WARNING and INFO as well.
=> Adding DNAC log levels for Discovery and PnP

plugins/doc_fragments/intent_params.py
Since we are using the documentation of dnac_log_level in every intent modules and it is associated with the DNAC credentials, we are adding that part to the doc_fragments/intent_params.py
=> Added the dnac_log_level documentation in the doc_fragments.intent_params.py file

plugins/modules/device_credential_intent.py, plugins/modules/network_settings_intent.py, plugins/modules/provision_intent.py, plugins/modules/site_intent.py, plugins/modules/template_intent.py
Removed the dnac_log_level from the documentation part because it is added in the global documentation part (doc_fragments/intent_params.py)
=> Removed the dnac_log_level from the documentation.

plugins/module_utils/dnac.py
**PR Summary**
Changes have been strictly in dnac.py 
- Supports logging using both 
self.log(message, 'INFO')
self.dnac_file_logger.info(message)
- Added a setup_logger method which configures the logger to the specified dnac_log_file_path and sets the logging level based on the specidied dnac_log_level. Also added the filename:function:lineno in the logger formatter directly, no need to add it in every message. 
- Have retained the def log() method for backward compatibility till we change the log lines in all the method
- Also, handles the situation if dnac_log is False and we are using seld.dnac_file_logger directly.
=> Setup a logger method

plugins/modules/discovery_intent.py
**Problem description:** 
1. CIDR based discovery should have Ip passed as IP/{prefix length} instead of passing prefix length separately.
2. Coding error in the for loop of multi range discovery
3. Deletion of all the discoveries at one go
**Fix:** For te fix we have added / based string formation, have taken care of for loop based issues and delete_all is a new parameter that can delete all the discoveries if someone tries to delete all the discoveries
**Test cases:** Have tested delete all, single deletion and CIDR based discovery
=> Changes for typos, fixed CIDR issue and added delete all feature

plugins/modules/device_credential_intent.py, plugins/modules/discovery_intent.py, plugins/modules/inventory_intent.py, plugins/modules/pnp_intent.py, plugins/modules/provision_intent.py, plugins/modules/site_intent.py, plugins/modules/swim_intent.py, plugins/modules/template_intent.py
1. Added the documentation part for the dnac_log_file_path and dnac_log_append.
2. Defined the dnac_log_file_patha nd dnac_log_append in the elem_spec.
3. Added the missing documentation for the import type in the tempalte_intent.py module.
=> Added the documentation part for dnac_log_file_path, dnac_log_append, Added the missing type in import documentation for template_intent module

plugins/doc_fragments/intent_params.py
Added the dnac_log_file_path, dnac_log_append common intent documentation file
Changed the dnac_log_level documentation - Clearly explained the dnac_log_level parameters
=> Added the dnac_log_file_path, dnac_log_append common intent documentation file

plugins/modules/discovery_intent.py
Problem: If we are having null values in credentials (v2) it throws nonetype error. Also, we have issues in API if the start_index > 500.
Fix: Made null to empty list for resolution of the error related to credentials. For API, I have added one more case which dynamically checks the records_to_return. Additionally, have added documentation for the HTTP credentials dict.
Test cases: Muti range with records_to return value of 720 and empty SNMP lists for failure.
=> Fixes for SNMP issue and records to return value

playbooks/discovery_workflow_manager.yml, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
Problem: Current discovery module creates confusion for the user while providing discovery specific credentials, due to ambiguous names like snmp_priv_passphrase.
Fix: Have segregated all the discovery specific credentials under one umbrella called discovery_specific_credentials, which takes care of credentials like CLI, SNMPv2 read, write, HTTP read , write and SNMPv3.
Test cases: Have tested for various discovery specific credentials.
1. snmpv2 read
2. snmpv2 write
3. snmpv3
4. cli 
5. http read
6. Combining all the above cases
=> Making changes to incorporate discovery specific credentials

plugins/modules/pnp_intent.py, plugins/modules/pnp_workflow_manager.py
Problem: If Image is absent in the Cisco Catalyst Center, no error is thrown.
Fix: Have added a check for the length of image_list we fetch from the API get all software details. If the length is 0, it will throw a message showing that either image is absent or is not golden tagged, making the user aware of the possible issues.
Test cases: 1. With Cisco Catalyst 9800 WLC with wrong image name (Failed)
2.  With Cisco Catalyst 9800 WLC with correct image name but not golden tagged (Failed)
3. With Cisco Catalyst 9800 WLC with correct image name and golden tagged (Passed)
=> Adding fix for SWIM upgrade in PnP

playbooks/discovery_intent.yml, playbooks/discovery_workflow_manager.yml, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
Problem: 1. Option to perform Discovery with any of the Snmp credentials.
2.  Option to perform Discovery with global credentials of user's choice.
3. Intermittent failure of discovery in Starting State.
Fix: 1. Have removed the and condition for SNMP Read and write and SNV3 to be present together.
2. Have added option to remove Discovery with multiple global credentials as list.
3. Have added an extra condition which checks the failure when the discovery undergoes Inventory Service.
Test Cases: 1. Execute discovery devices using MULTI RANGE with various global credentials
2. Execute discovery of single device using various discovery specific credentials
3. Execute discovery devices using MULTI RANGE with various discovery specific credentials
4. Execute discovery devices using …
=> Adding option to specify global credentials while performing discovery

plugins/modules/pnp_intent.py, plugins/modules/pnp_workflow_manager.py
1.  **Git PR Link**: https://github.com/madhansansel/dnacenter-ansible/pull/181
2.  **Problem Description**: When we provide an invalid image name/site details, we see an error coming on the GUI, without proper error handling.
3.  **Root Cause:** We tried to perform PnP of a EWLC using an invalid image. The device was not added in the PnP database. We tried to claim it just after adding it to the PnP database.
4.  **Code Changes:** Called get_have method in get_diff_merged to fetch the site/image values post adding it to the PnP database.
5.  **Testing and Automation:**
_PnP.yml_
TASK [Claim an existing Wireless Controller, apply a template, and upgrade its image for a specified site] *********************************************************************************************
task path: …
=> Fixing Invalid SWIM issue while claiming

plugins/modules/template_intent.py, plugins/modules/template_workflow_manager.py
Review - 1 [04-03-2024 (DD/MM/YYYY]
The language enum - ["JINJA", "VELOCITY"] is checking the name not the language.
While passing language other than 'JINJA' and 'VELOCITY', no error is getting triggered.
Changed the name_list = ["JINJA", "VELOCITY"] to language and corrected the mismatched name and language by interchanging the 'name' and 'language'.
Passed the language input other than 'JINJA' and 'VELOCITY' and the error is getting triggered.
=> Fixed the language enum check for the name instead of language

playbooks/discovery_intent.yml, playbooks/discovery_workflow_manager.yml, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
Problem: The user should have the choice of using/not using global credentials while performing discovery.
Fix: Have added a new parameter called use_global_cred which if False, doesn't use any global credentials to perform discovery.
Test cases:
1. Execute discovery devices using MULTI RANGE with various global credentials
2. Execute discovery of single device using various discovery specific credentials and all the global credentials
3. Execute discovery of single device using various discovery specific credentials only
4. Execute discovery devices using MULTI RANGE with various discovery specific credentials
5. Execute discovery devices using CDP/LLDP/CIDR
6. Execute deletion of single discovery from the dashboard
7. Execute deletion of all the discoveries from the dashboard
=> Adding the feature of non-mandatory global credentials

plugins/modules/pnp_intent.py, plugins/modules/pnp_workflow_manager.py
1.  **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/187
2.  **Problem Description**: Whenever the user tries to claim a Stack Switch using the playbook and tries to edit the device info like hostname/serial_number/pid, then it automatically gets converted to a normal switch.
3.  **Root Cause:** This conversion happens due to a bug in the update_device API under PnP, which automatically makes stack as False if not passed in the payload.
4.  **Code Changes**: Have added a check for the stack. If the device is a stack, it automatically takes stack as True for passing the payload to the API, bypassing the bug.
5. **Testing and Automation**: For testing I added a test case for claiming a stack switch by passing PnP type as "StackSwitch" in the playbook. It passed …
=> Adding fix for Stackswitch getting changed to normal switch post editing the device's info

plugins/modules/pnp_intent.py, plugins/modules/pnp_workflow_manager.py
1.   Git PR Link: https://github.com/madhansansel/dnacenter-ansible/pull/193
2.   Problem Description: Claiming an EWLC with a template is nit supported in Cisco Catalyst Center 235x.
3.   Root cause: Feature was introduced post 237x.
4.   Fix: Have added the same in the documentation
=> Adding documentation for the EWLC template issue in CCC 235x

playbooks/template_workflow_manager.yml, plugins/modules/template_workflow_manager.py
Review - 1 [26-03-2024 (DD/MM/YYYY]
**Bug fix**
Missing ``op_modifies=True`` in response = self.dnac._exec()
While passing the validate_response_schema = False, the active_validation is not turning off(still validating the response schema)
Added the 'op_modifies=True' to all the necessary SDK calls in the module. 
Passed the validate_response_schema = False and checked without the acitve_validation is set to True or False. It is set to False. Hence the response schema is not getting validated.
**Result structure**
Changed the self.result structure - made it into three partition 
1. 'configurationTemplate' for project/template creation or updation or deletion
2. 'export' for exporting the project/template
3. 'import' for importing the project/template
=> Added the op_modifies=True for turning off the active validation and changed the result structure

plugins/module_utils/dnac.py, plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
**Problem description:** Validity of IPv4 addresses are there on GUI. Similar check needs to be added in modules as well.
**Fix:** Have added a method in dnac.py file called is_valid_ip which takes an ip address as input and returns True if it is valid else it returns False. Have implemented the same in discovery module as well.
**Test cases**: Returned False for IP addresses like 204.1.1.900, 204.1.1.80-204.1.1.900, 204.1.1.80-204.1.1.79 (Reverse range is not allowed)
=> Adding method to check valid ip address

plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
1. **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/214
2.  **Problem Description:** The process goes into an infinite loop once we abort the discovery on GUI.
3.  **Root Cause:** We didn't handle the case of "Aborted" discovery condition.
4.  **Code Changes:** Have added a code a check inside the while loop, with an elif condition to check the discovery_c onfition. Along with that, have added a flag to check the aborted state specifically.
5.  **Testing and Automation:** Have tested a discovery by aborting it on the GUI. The following output was collected on the CLI.
TASK [Discovery devices from a CDP seed] **************************************************************************************************************************************************
task path: …
=> Adding fix for Infinite Loop Issue while aborting a discovery

plugins/modules/inventory_intent.py, plugins/modules/inventory_workflow_manager.py
In this commit - 
-- Enhanced log messages for updating device role of multiple devices in which some of the devices are already updated but  log messages show that all devices role updated successfully with changed =1 in output.
=> Enhanced log result messaged for updating role of multiple devices

plugins/modules/provision_workflow_manager.py
1. **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/222
2.  **Problem Description:** The exception comes while trying to provision a device Exception: An error occured when executing operation. The error was: [400] Bad Request - This device is not provisioned to any site. deviceManagementIpAddress = 204.1.2.5.
3.  **Root Cause:** Try and error was not handled for get wired provisioned devices API.
4.  **Code Changes:** Have added a try and except block.
5.  **Testing and Automation:**  This is the logs for the execution of Provision Workflow.
TASK [Provision a wired device to a site] ********************************************************************************************************************************************************
task path: …
=> Adding try and error exception for provision module

playbooks/configs_backup.yml, plugins/modules/device_configs_backup_workflow_manager.py
**Problem description:** Taking the backup of the running configurations present in the Cisco Catalyst Center's Inventory.
**Fix:** Have added device_configs_backup_workflow manager module along with the sample playbook.
**Design considerations:** User wants to export the configs to his/her local system.
**Test cases:** Tested for single device and multiple devices using family (Switches and Hubs).
=> Adding module for device config backup

plugins/modules/inventory_intent.py, plugins/modules/inventory_workflow_manager.py
In this commit - 
-- Fix the documentation of inventory module while adding/updating device, cli_transport should be ssh or telnet instead of SSH or Telnet.
=> Update the cli_transport type in documentaion to ssh/telnet

plugins/modules/network_settings_workflow_manager.py
Fixed the problem with the slaacSupport
Previously it was set to True and not reacting to the playbook input given by the user.
Now while creating the slaacSupport will act according to the user input.
=> Fixed the problem with the slaacSupport

playbooks/network_settings_workflow_manager.yml, plugins/modules/network_settings_workflow_manager.py
Added clear description for the documentation for the network functions
Made the protocol and the servers set to the default value rather than throwing an error for it.
=> Added clear description for the documentation for the network functions

plugins/modules/provision_workflow_manager.py
Problem: For few cases where we want to re-provision a wired device, we see that it goes into the progress as TASK_MODIFY_PUT. Due to not handling the case properly, it may lead to the task getting stuck inside the while loop endlessly.
Fix: Have added TASK_MODIFY_PUT check in the if check of get_task_status method.
=> Adding the condition for put API of wired device

plugins/modules/device_credential_workflow_manager.py
Delete all the config even a error occurs in the middle
=> Delete all the config even a error occurs in the middle

plugins/modules/network_compliance_workflow_manager.py
**PR Summary:**
- Code changes have been made to **plugins/modules/network_compliance_workflow_manager.py** file only. 
- Includes 1 Bug Fix:
1. Compliance error msg when there are no devices in given sites not clear
- Tested on Catalyst Centre v2.3.7.0.
=> 1 Bug Fix - Network Compliance Module

plugins/module_utils/dnac.py, plugins/modules/device_credential_workflow_manager.py, plugins/modules/ise_radius_integration_workflow_manager.py, plugins/modules/network_settings_workflow_manager.py, plugins/modules/template_workflow_manager.py
Added the maximum timeout for checking the execution of task id and execution id
=> Added the maximum timeout for checking the execution of task id and execution id

plugins/modules/provision_workflow_manager.py
1. **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/294
2.  **Problem Description:** There is a potential error when we try to fetch the list using get_membership API to see whether a device is associated with a site.
3.  **Root Cause:** The Get_site_assignment function should handle cases where the relevant data might be missing or None. It should either gracefully return a default value or raise a more informative exception to indicate the issue.
4.  **Code Changes:** Have added a new method which uses the API 'get_device_detail'
=> adding alternative of get_memebership API

plugins/module_utils/dnac.py, plugins/modules/events_and_notifications_workflow_manager.py, plugins/modules/inventory_intent.py, plugins/modules/inventory_workflow_manager.py, plugins/modules/swim_intent.py, plugins/modules/swim_workflow_manager.py
In this commit -
-- Fix the issue of removing header from existing Webhook destination as part of update operation by passing an empty list in the playbook.
-- Also fix the issue with updating webhook destination with headers.
-- Fix the issue of getting devices from inventory if it's more than 500 as 'get_device_list' API only fetch 500 devices at a time because of which module like inventory and swim gets failed.
=> Fix the issue of removing header while configuring webhook destination

plugins/modules/discovery_intent.py, plugins/modules/discovery_workflow_manager.py
1. **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/317
2. **Problem Description:** Currently, if prefix is not between 20 and 30 the error comes something like this " Invalid prefix length for CIDR discovery or total number of IP''s exceeds 4096 limit". Instead of this, it should be handled like that in UI.
3. **Root Cause**: Haven't done proper error handling.
4. **Code Changes**: Added  a case to check the prefix length.
5. **Testing**: Have tested it on outside 20-30 range and inside 20-30 range.
=> Fix for prefix length check

plugins/modules/provision_workflow_manager.py
1. **Git PR Link:** https://github.com/madhansansel/dnacenter-ansible/pull/323
2. **Problem Description:** Grammatically incorrect documentation of get_dev_type function under the doc string.
3. **Root Cause**: Has been overlooked while writing.
4. **Code Changes**: Fixed it with line "Post creation of the validated input, we use this method to get the type of the device".
5. **Testing**: Testing is not required since its a documentation change.
=> Correcting docstring documentation of get_dev_type function

plugins/modules/device_configs_backup_workflow_manager.py
Added the fix where devices being AP or being in unmanaged state or being in unreachable state, won't be going for the device config backup. For the same, I added a few conditions by looping through the device list retrieved via 'get device list' API.
=> Fix for unreachable devices, Ap devices and unmanaged devices backup

plugins/modules/rma_workflow_manager.py
The bug [CSCwm26351] The RMA process can use a mix of various identifiers like device name, IP address, and serial number is addressed in this commit.
- [ yes ] …
=> rma_workflow_manager bug fixed

plugins/modules/rma_workflow_manager.py
The below issues are fixed
1 The bulk RMA return log only returns for one process and is not clear
2 Replace devices with faulty devices that have been manually marked for replacement before not work
3 RMA need pre-check before trigger RMA workflow
4 The function 'return_replacement_devices_with_details' does not work correctly with the filter
5 The function 'def verify_diff_replaced()' does not operate reliably
- [ yes ] My changes generate …
=> RMA workflow bugs fixed

plugins/module_utils/dnac.py, plugins/modules/accesspoint_workflow_manager.py
36103 - Access-Point Configuration: Need support for bulk operations
42969 - Providing string value for LED Brightness level parameter results in module error
=> Bulk update bug fixed

plugins/modules/network_settings_workflow_manager.py
Fix for the missing conditional check for network_aaa and client_and_endpoint_aaa
When checking for the requires update we the update for the following changes
1. If the user provides shared_secret key under the network_aaa
2. If the user provides shared_secret key under the client_and_endpoint_aaa
3. If there is a difference between the user config and CCC config.
For 1 and 2, additional validations were added.
=> Fix for the missing conditional check for network_aaa and client_and_endpoint_aaa

plugins/modules/network_settings_workflow_manager.py
Corrected the documentation of reserve_pool_details
The reserve_pool_details was a list but in the documentation it is mentioned as a dict.
Changed the type from dict to list and added the elements type as dict (which is the type of the elements).
=> Corrected the documentation of reserve_pool_details

plugins/modules/accesspoint_workflow_manager.py, tests/unit/modules/dnac/fixtures/accesspoint_workflow_manager.json
59877 - Access Points: Observing irrelevant error message when configuring cable loss
=> Access Point Cable loss bug has been updated

plugins/modules/user_role_workflow_manager.py
The below issue is fixed
Unclear Error Message for Missing Mandatory Field in User Creation
- [ yes ] All the sanity checks have been completed and the sanity test …
=> User and Role bug fixed

plugins/modules/inventory_workflow_manager.py
Bug fixed for Inventory - Update device return message and status are not correct
=> Inventory Bug fixed

plugins/modules/rma_workflow_manager.py
Bug fixed - NoneType' object is not subscriptable in Catalyst Center version 2.3.5.6
=> rma workflow manager bug fixed

plugins/modules/network_settings_workflow_manager.py
Fix for below issues:
- IPv4 prefix length is required even after setting IPv4 prefix to False
- Unable to create subpool using Total host (Number of IP Addresses)
- [ Yes] Bug fix
- [ No] New feature
- [No ] Breaking change
- [ No] Documentation update
- [ Yes] My code follows the style guidelines of this project
- [ Yes] I have performed a self-review of my own code
- [ Yes] I have commented my code, particularly in hard-to-understand areas
- [ Yes] I have made corresponding changes to the documentation
- [Yes ] My changes generate no new warnings
- [ No] I have added tests that prove my fix is effective or that my feature works
- [ Yes] New and existing unit tests pass locally with my changes
- [ Yes] Any dependent changes have been merged and published in downstream modules
- [ Yes] …
=>  IPv4 prefix length is required even after setting IPv4 prefix to False

plugins/modules/sda_fabric_devices_workflow_manager.py
Ordered the device_config details before removing the devices from the fabric
Because the first node that should be added to the fabric is a CONTROL_PLANE_NODE and the last should be deleted from the fabric is also the CONTROL_PLANE_NODE.
If user passes series of devices that to be removed from the fabric, we will order it in such a way that the CONTROL_PLANE_NODE should be removed at last from the fabric.
=> Ordered the device_config details before removing the devices from the fabric

plugins/modules/sda_fabric_devices_workflow_manager.py
Removed the check for the provisioning status of the WLC.
Since we dont have the API for the finding whether the WLC is provisioned or not.
We will just ignore the provisioning check for the WLC alone.
It will added again in the 2.3.7.9 SDK release.
=> Removed the check for the provisioning status of the WLC
